In [4]:
# NUMPY PACKAGE

* used for manipulating arrays
* compute lot of values for analysis
* pre-process data



SyntaxError: invalid syntax (852172262.py, line 3)

# Importing Numpy

In [ ]:
import numpy as np

# Using Numpy

In [ ]:
array_a = np.array([1, 2, 3])
array_a

In [6]:
array_b = np.array([4, 5, 6])
array_b

array([4, 5, 6])

[numpy docs](https://numpy.org/doc/stable/)

In [ ]:
np.mean(array_b)

In [9]:
#mean of rows = axis = 1

array_hw_2 = np.array([[4,5],[7,10]])

np.mean(array_hw_2, axis =1)

array([4.5, 8.5])

In [12]:
#adding data type as integer

np.mean(array_hw_2, axis = 0, dtype = int)
 


array([5, 7])

In [10]:
#mean of columns = axis = 0

array_hw_2 = np.array([[4,5],[7,10]])

np.mean(array_hw_2, axis =0)

array([5.5, 7.5])

[numpy docs](https://numpy.org/doc/stable/)

# PANDAS

pandas = panel data

uses:
* analyze data set
* import export data

# IMPORTING PANDAS

In [13]:
import pandas as pd

# PANDAS SERIES

In [15]:
products = ['A', 'B', 'C', 'D']
products

['A', 'B', 'C', 'D']

In [16]:
type(products)

list

In [20]:
product_categories = pd.Series(products)

In [21]:
product_categories

#object is the default dtype if not numeric

0    A
1    B
2    C
3    D
dtype: object

In [22]:
type(product_categories)

pandas.core.series.Series

In [24]:
type(pd.Series(products))

pandas.core.series.Series

In [26]:
daily_rate_dollars = pd.Series([40, 45, 50, 60])
daily_rate_dollars

0    40
1    45
2    50
3    60
dtype: int64

In [27]:
print(daily_rate_dollars)

0    40
1    45
2    50
3    60
dtype: int64


In [28]:
import numpy as np

In [31]:
array_a = np.array([10, 20, 30, 40, 50])
array_a


array([10, 20, 30, 40, 50])

In [32]:
type(array_a)

numpy.ndarray

In [36]:
series_a = pd.Series(array_a)
series_a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [37]:
type(series_a)

pandas.core.series.Series

In [38]:
series_a.dtype

dtype('int64')

In [42]:
type(series_a)


pandas.core.series.Series

In [41]:
series_a.size

5

In [43]:
product_categories.dtype

dtype('O')

In [44]:
product_categories.size

4

In [48]:
print(product_categories.name)

Product Categories


In [49]:
product_categories.name = "Product Categories"
product_categories

0    A
1    B
2    C
3    D
Name: Product Categories, dtype: object