**Business** - organization that exists to make money

**Data** - information gathered for reference

**Qualitative Data** - form of text and descriptive in nature (not a number)

**Quantitative Data** - numeric data

**Analysis** - sepaaration of a whole data into smaaller, digestable components to be studied individually, any dataset that contains past data

**Analytics** - future performance -> analysis + logical and computational reasoning

**Business Intelligence** - studies the past of a company, analyzing relational databases

**Data Science** - often involves machine learning, advance statistics and regression analysis




matrix - [x,y,z], [x,y,z]

vector - [x, y] (Row, column)

scalar = point


# MATRIX

In [6]:
#Sample Matrix

import numpy as np

m = np.array([[5,12,6],[-3,0,14]])
m


array([[ 5, 12,  6],
       [-3,  0, 14]])

# DATA SHAPES

In [7]:
m.shape

(2, 3)

# DATA TYPE

In [8]:
type(m)

numpy.ndarray

# VECTOR

In [9]:
v = np.array([5, 2, 7])
v

array([5, 2, 7])

In [11]:
v.shape

(3,)

**RESHAPE - gives an array a new shape**

In [12]:
v.reshape(3,1)

array([[5],
       [2],
       [7]])

Tensor Rank 0 - scalar

Tensor Rank 1 - vector (m x 1)

Tensor Rank 2 - matrix (m x n)

Tensor Rank 3 - (k x m x n)

In [15]:
m1 = np.array([[3, 2, 4], [7, 8, 5]])
m1


array([[3, 2, 4],
       [7, 8, 5]])

In [14]:
m2 = np.array([[6, 3, 5], [5, 7, 4]])
m2

array([[6, 3, 5],
       [5, 7, 4]])

In [16]:
t = np.array([m1, m2])
t

array([[[3, 2, 4],
        [7, 8, 5]],

       [[6, 3, 5],
        [5, 7, 4]]])

In [18]:
#(k, m, n)
#k = number of matrix
#m = number of rows
#n = number of columns
t.shape

(2, 2, 3)